--- #YAML:1.0
name:                XML-RPC-Fast
version:             0.1
abstract:            Faster implementation for an XML-RPC client and server (based on XML::RPC)
license:             ~
author:              
    - Mons Anderson <mons@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    LWP::UserAgent:                0
    Test::More:                    0
    XML::Parser:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
